#!/usr/bin/env bash

# Copyright 2019 Gary Yu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script contains test-related jobs.

case "${CI_JOB}" in
    "test")
        for arch in ${CI_JOB_ARGS}; do
            printf "executing build for \`%s\`...\n" "${arch}"
            cd rust && cargo lipo --release --targets "${arch}"-apple-ios && cd - > /dev/null || exit 1
            ls -l rust/target/${CI_JOB_ARGS}-apple-ios/release/libgrinwallet.a || exit 1
            printf "package 'libgrinwallet.a' generated successfully\n"
        done
        ;;
esac

